// Generated by CoffeeScript 1.6.3
(function() {
  var Xenophos, addToCurrentPanes, bindClickEvents, buildNavFunctions, buildPortraitFor, clearAllCurrentPanes, currentPanes, exitPage, getCurrentPanes, howWeDidIt, loadpage, meetUs, removeFromCurrentPane, setAndBindHowPageSizes, setAndBindTextWidthSize, showSpecificBio,
    __slice = [].slice;

  Xenophos = [
    {
      firstname: "Alex",
      lastname: "Lenail",
      tags: ["Co-founder", "Light-painter", "Webmaster"]
    }, {
      firstname: "Bradford",
      lastname: "Thorne",
      tags: ["Co-founder", "Light-painter", "Photographer"]
    }, {
      firstname: "Max",
      lastname: "Lenail",
      tags: ["Co-founder", "Lead Photographer"]
    }, {
      firstname: "Anna",
      lastname: "McGarrigle",
      tags: ["Photographer", "Web Designer"]
    }, {
      firstname: "Masha",
      lastname: "Andreyeva",
      tags: ["Photographer", "Light-painter"]
    }, {
      firstname: "Arun",
      lastname: "Varma",
      tags: ["Photographer", "Light-painter"]
    }, {
      firstname: "Gregory",
      lastname: "Dunn",
      tags: ["Light-painter"]
    }, {
      firstname: "Tiffany",
      lastname: "Tsung",
      tags: ["Light-painter"]
    }, {
      firstname: "Paige",
      lastname: "Morkner",
      tags: ["Light-painter"]
    }, {
      firstname: "Eric",
      lastname: "Theis",
      tags: ["Light-painter"]
    }, {
      firstname: "Kevin",
      lastname: "Lee",
      tags: ["Light-painter"]
    }, {
      firstname: "Jason",
      lastname: "Liang",
      tags: ["Light-painter"]
    }
  ];

  currentPanes = [];

  addToCurrentPanes = function() {
    var pane, panes, _i, _len, _results;
    panes = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = panes.length; _i < _len; _i++) {
      pane = panes[_i];
      _results.push(currentPanes.push(pane));
    }
    return _results;
  };

  removeFromCurrentPane = function(pane) {
    return currentPanes.splice(indexOf(pane), 1);
  };

  clearAllCurrentPanes = function() {
    return currentPanes = [];
  };

  getCurrentPanes = function() {
    return currentPanes;
  };

  loadpage = function() {
    var what, who;
    buildNavFunctions();
    bindClickEvents();
    setAndBindTextWidthSize();
    $("#headerBar").hide().fadeIn(1000);
    who = $("#who").hide().fadeIn(1000);
    what = $("#what").hide().fadeIn(1000);
    return addToCurrentPanes(who, what);
  };

  $(document).ready(function() {
    return loadpage();
  });

  buildNavFunctions = function() {
    $("#Gallery").click(function() {
      return exitPage("gallery.html");
    });
    $("#Contact").click(function() {
      return exitPage("404.html");
    });
    return $("#headerBarLogo").click(function() {
      return exitPage("index.html");
    });
  };

  bindClickEvents = function() {
    $("#meet").click(function() {
      $("#what, #who").fadeOut(400);
      clearAllCurrentPanes();
      return meetUs();
    });
    return $("#how").click(function() {
      $("#what, #who").fadeOut(400);
      clearAllCurrentPanes();
      return howWeDidIt();
    });
  };

  setAndBindTextWidthSize = function() {
    var setTextWidthSize;
    setTextWidthSize = function() {
      var w;
      w = $(window).width();
      if (w > 1400) {
        return $(".text").css({
          width: "20%"
        });
      } else if (w > 1200) {
        return $(".text").css({
          width: "30%"
        });
      } else if (w > 900) {
        return $(".text").css({
          width: "40%"
        });
      } else {
        return $(".text").css({
          width: "60%"
        });
      }
    };
    $(window).bind('resize', function() {
      return setTextWidthSize();
    });
    return setTextWidthSize();
  };

  meetUs = function() {
    var person, setPortraitWidth, _i, _len;
    $("#meet").unbind();
    addToCurrentPanes($("#people").removeClass("hidden"));
    setPortraitWidth = function() {
      var width;
      width = $(window).width();
      if (width < 1200) {
        return $(".portrait").width("33%");
      } else if (width < 1700) {
        return $(".portrait").width("24.75%");
      } else {
        return $(".portrait").width("16.35%");
      }
    };
    $(window).bind('resize', function() {
      return setPortraitWidth();
    });
    for (_i = 0, _len = Xenophos.length; _i < _len; _i++) {
      person = Xenophos[_i];
      buildPortraitFor(person);
    }
    setPortraitWidth();
    $(".portraits").each(function() {
      return setTimeout((function() {
        return $(this).addClass("popIn");
      }), 200);
    });
    return $('html, body').animate({
      scrollTop: $("#headerBar").height() + 60
    }, 1000);
  };

  buildPortraitFor = function(person) {
    var $image, $nametag, $portrait, name, tags;
    $portrait = $("<div/>", {
      "class": "hidden portrait",
      id: "" + person.firstname
    });
    $image = $("<img/>", {
      src: "images/about/icons/" + person.firstname + ".jpg"
    });
    name = "<h1>" + person.firstname + " " + person.lastname + "</h1>";
    tags = "<p>" + person.tags.join(", &nbsp") + "</p>";
    $nametag = $("<div/>", {
      "class": "nametag"
    }).append(name).append(tags);
    $portrait.append($image).append($nametag);
    $("#people").append($portrait);
    $portrait.removeClass("hidden").addClass("popIn");
    return $portrait.click(function() {
      return showSpecificBio(person.firstname);
    });
  };

  showSpecificBio = function(name) {
    var $div, pane, _fn, _i, _len, _ref;
    if (name === "Alex") {
      $div = $("#Alex_Lenail");
    } else if (name === "Bradford") {
      $div = $("#Bradford_Thorne");
    } else if (name === "Max") {
      $div = $("#Max_Lenail");
    } else if (name === "Anna") {
      $div = $("#Anna_McGarrigle");
    } else if (name === "Masha") {
      $div = $("#Masha_Andreyeva");
    } else if (name === "Arun") {
      $div = $("#Arun_Varma_Gregory_Dunn");
    } else if (name === "Gregory") {
      $div = $("#Arun_Varma_Gregory_Dunn");
    } else if (name === "Tiffany") {
      $div = $("#Tiffany_Tsung_Paige_Morkner_Eric_Theis");
    } else if (name === "Paige") {
      $div = $("#Tiffany_Tsung_Paige_Morkner_Eric_Theis");
    } else if (name === "Eric") {
      $div = $("#Tiffany_Tsung_Paige_Morkner_Eric_Theis");
    } else if (name === "Kevin") {
      $div = $("#Kevin_Lee_Allen_Lee_Jason_Liang");
    } else if (name === "Jason") {
      $div = $("#Kevin_Lee_Allen_Lee_Jason_Liang");
    } else {
      throw new Error("Name unrecognized");
    }
    _ref = getCurrentPanes();
    _fn = function(pane) {
      return pane.fadeOut(400);
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      pane = _ref[_i];
      _fn(pane);
    }
    $div.removeClass("hidden");
    return $div.children().each(function() {
      return void 0;
    });
  };

  howWeDidIt = function() {
    $("#meet").unbind();
    addToCurrentPanes($("#method").removeClass("hidden"));
    return setAndBindHowPageSizes();
  };

  setAndBindHowPageSizes = function() {
    var setFontSize, setMargins, setTitleFontSize;
    setTitleFontSize = function() {
      var s;
      s = Math.floor($("#teachingMasha").height() / 6);
      return $(".title, #inspiTitle").css({
        "font-size": s
      });
    };
    setMargins = function() {
      var w;
      w = $(window).width();
      if (w < 1000) {
        $("article").css({
          left: "5%",
          right: "5%",
          width: "90%"
        });
        $(".aboutImage").css({
          width: "96%"
        });
        $(".tool").css({
          right: "45%",
          width: "50%"
        });
        $(".tool-text").css({
          width: "40%",
          left: "50%"
        });
        $("#actionTitleImage").css({
          width: "90%",
          left: "5%"
        });
        $("#actionText").css({
          width: "26%",
          top: "20%",
          left: "58%"
        });
        return $(".inspirationImage").css({
          width: "90%"
        });
      } else {
        $("article").css({
          left: "30%",
          right: "30%",
          width: "40%"
        });
        $(".aboutImage").css({
          width: "80%"
        });
        $(".tool").css({
          right: "12%",
          width: "40%"
        });
        $(".tool-text").css({
          width: "25%",
          left: "55%"
        });
        $("#actionTitleImage").css({
          width: "50%",
          left: "10%"
        });
        $("#actionText").css({
          width: "22%",
          top: "26%",
          left: "62.5%"
        });
        return $(".inspirationImage").css({
          width: "80%"
        });
      }
    };
    setFontSize = function() {
      var size, titleSize, width;
      width = $(window).width();
      size = Math.floor(width / 180) * 2;
      titleSize = Math.floor(size * 0.6) * 2;
      if (size > 18) {
        $(".tool-text p, article p, #actionText, #settingText p").css({
          "font-size": size
        });
        return $(".tool-text h2, #settingText h2, .inspiration-link").css({
          "font-size": titleSize
        });
      } else {
        $(".tool-text p, article p, #actionText, #settingText p").css({
          "font-size": 18
        });
        return $(".tool-text h2, #settingText h2, .inspiration-link").css({
          "font-size": "1.5em"
        });
      }
    };
    $(window).bind('resize', function() {
      setTitleFontSize();
      setMargins();
      return setFontSize();
    });
    setTitleFontSize();
    setMargins();
    return setFontSize();
  };

  exitPage = function(destination) {
    var go;
    go = function() {
      return window.location.href = destination;
    };
    $("#headerBar").fadeOut(400);
    $(".pane").fadeOut(400);
    return window.setTimeout(go, 400);
  };

}).call(this);
