// Generated by CoffeeScript 1.6.3
(function() {
  var Xenophos, addToCurrentPanes, back, bindClickEvents, buildNavFunctions, buildPortraitFor, clearAllCurrentPanes, currentPanes, exitPage, getCurrentPanes, howWeDidIt, loadpage, meetUs, removeFromCurrentPane, setAndBindHowPageSizes, setAndBindWhoPageSizes, showSpecificBio,
    __slice = [].slice;

  Xenophos = [
    {
      firstname: "Alex",
      lastname: "Lenail",
      tags: ["Co-founder", "Light-painter", "Webmaster"]
    }, {
      firstname: "Bradford",
      lastname: "Thorne",
      tags: ["Co-founder", "Light-painter", "Photographer"]
    }, {
      firstname: "Max",
      lastname: "Lenail",
      tags: ["Co-founder", "Lead Photographer"]
    }, {
      firstname: "Anna",
      lastname: "McGarrigle",
      tags: ["Photographer", "Web Designer"]
    }, {
      firstname: "Masha",
      lastname: "Andreyeva",
      tags: ["Photographer", "Light-painter"]
    }, {
      firstname: "Arun",
      lastname: "Varma",
      tags: ["Photographer", "Light-painter"]
    }, {
      firstname: "Gregory",
      lastname: "Dunn",
      tags: ["Light-painter"]
    }, {
      firstname: "Tiffany",
      lastname: "Tsung",
      tags: ["Light-painter"]
    }, {
      firstname: "Paige",
      lastname: "Morkner",
      tags: ["Light-painter"]
    }, {
      firstname: "Eric",
      lastname: "Theis",
      tags: ["Light-painter"]
    }, {
      firstname: "Kevin",
      lastname: "Lee",
      tags: ["Light-painter"]
    }, {
      firstname: "Jason",
      lastname: "Liang",
      tags: ["Light-painter"]
    }
  ];

  currentPanes = [];

  addToCurrentPanes = function() {
    var pane, panes, _i, _len, _results;
    panes = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = panes.length; _i < _len; _i++) {
      pane = panes[_i];
      _results.push(currentPanes.push(pane));
    }
    return _results;
  };

  removeFromCurrentPane = function(pane) {
    return currentPanes.splice(indexOf(pane), 1);
  };

  clearAllCurrentPanes = function() {
    return currentPanes = [];
  };

  getCurrentPanes = function() {
    return currentPanes;
  };

  $(document).ready(function() {
    return loadpage();
  });

  loadpage = function() {
    var what, who;
    buildNavFunctions();
    bindClickEvents();
    setAndBindHowPageSizes();
    setAndBindWhoPageSizes();
    $("#headerBar").hide().fadeIn(1000);
    who = $("#who").hide().fadeIn(1000);
    what = $("#what").hide().fadeIn(1000);
    return addToCurrentPanes(who, what);
  };

  buildNavFunctions = function() {
    $("#Gallery").click(function() {
      return exitPage("gallery.html");
    });
    $("#Contact").click(function() {
      return exitPage("404.html");
    });
    return $("#headerBarLogo").click(function() {
      return exitPage("index.html");
    });
  };

  bindClickEvents = function() {
    $("#meet").click(function() {
      $("#what, #who").fadeOut(400);
      clearAllCurrentPanes();
      return meetUs();
    });
    $("#how").click(function() {
      $("#what, #who").fadeOut(400);
      clearAllCurrentPanes();
      return howWeDidIt();
    });
    $("#About").click(function() {
      return back();
    });
    return $(".backButton").click(function() {
      return back();
    });
  };

  meetUs = function() {
    var $people, person, _i, _len;
    $people = $("#people");
    $people.children().each(function() {
      return $(this).remove();
    });
    $people.removeClass("hidden").fadeIn(1);
    addToCurrentPanes($people);
    for (_i = 0, _len = Xenophos.length; _i < _len; _i++) {
      person = Xenophos[_i];
      buildPortraitFor(person);
    }
    setAndBindWhoPageSizes();
    return $('html, body').animate({
      scrollTop: 160
    }, 1000);
  };

  buildPortraitFor = function(person) {
    var $image, $nametag, $portrait, name, tags;
    $portrait = $("<div/>", {
      "class": "hidden portrait",
      id: "" + person.firstname
    });
    $image = $("<img/>", {
      src: "images/about/icons/" + person.firstname + ".jpg"
    });
    name = "<h1>" + person.firstname + " " + person.lastname + "</h1>";
    tags = "<p>" + person.tags.join(", &nbsp") + "</p>";
    $nametag = $("<div/>", {
      "class": "nametag"
    }).append(name).append(tags);
    $portrait.append($image).append($nametag);
    $("#people").append($portrait);
    $portrait.removeClass("hidden").addClass("popIn");
    return $portrait.click(function() {
      return showSpecificBio(person.firstname);
    });
  };

  showSpecificBio = function(name) {
    var $div, oldPane, _i, _len, _ref;
    if (name === "Alex") {
      $div = $("#Alex_Lenail");
    } else if (name === "Bradford") {
      $div = $("#Bradford_Thorne");
    } else if (name === "Max") {
      $div = $("#Max_Lenail");
    } else if (name === "Anna") {
      $div = $("#Anna_McGarrigle");
    } else if (name === "Masha") {
      $div = $("#Masha_Andreyeva");
    } else if (name === "Arun") {
      $div = $("#Arun_Varma_Gregory_Dunn");
    } else if (name === "Gregory") {
      $div = $("#Arun_Varma_Gregory_Dunn");
    } else if (name === "Tiffany") {
      $div = $("#Tiffany_Tsung_Paige_Morkner_Eric_Theis");
    } else if (name === "Paige") {
      $div = $("#Tiffany_Tsung_Paige_Morkner_Eric_Theis");
    } else if (name === "Eric") {
      $div = $("#Tiffany_Tsung_Paige_Morkner_Eric_Theis");
    } else if (name === "Kevin") {
      $div = $("#Kevin_Lee_Allen_Lee_Jason_Liang");
    } else if (name === "Jason") {
      $div = $("#Kevin_Lee_Allen_Lee_Jason_Liang");
    } else {
      throw new Error("Name unrecognized");
    }
    _ref = getCurrentPanes();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      oldPane = _ref[_i];
      oldPane.fadeOut(400);
    }
    $div.removeClass("hidden").fadeIn(600);
    $div.children().each(function() {
      return $(this).removeClass("hidden").fadeIn(600);
    });
    return addToCurrentPanes($div);
  };

  howWeDidIt = function() {
    addToCurrentPanes($("#method").removeClass("hidden").fadeIn(1));
    setAndBindHowPageSizes();
    return $("#method").append(backButton());
  };

  back = function() {
    var newPane, next, oldPane, oldPanes, _i, _j, _len, _len1, _results;
    oldPanes = getCurrentPanes();
    if (oldPanes[0].selector === "#people" && (oldPanes[1] != null)) {
      next = [$("#people")];
    } else {
      next = [$("#who"), $("#what")];
    }
    for (_i = 0, _len = oldPanes.length; _i < _len; _i++) {
      oldPane = oldPanes[_i];
      oldPane.fadeOut(400);
    }
    clearAllCurrentPanes();
    _results = [];
    for (_j = 0, _len1 = next.length; _j < _len1; _j++) {
      newPane = next[_j];
      newPane.fadeIn(400);
      _results.push(addToCurrentPanes(newPane));
    }
    return _results;
  };

  setAndBindWhoPageSizes = function() {
    var setPortraitWidth, setSpecificPeopleStyles, setTextWidthSize;
    setTextWidthSize = function() {
      var width;
      width = $(window).width();
      if (width > 1400) {
        return $(".text").css({
          width: "20%"
        });
      } else if (width > 1200) {
        return $(".text").css({
          width: "30%"
        });
      } else if (width > 900) {
        return $(".text").css({
          width: "40%"
        });
      } else {
        return $(".text").css({
          width: "60%"
        });
      }
    };
    setPortraitWidth = function() {
      var width;
      width = $(window).width();
      if (width < 800) {
        return $(".portrait").width("49.7%");
      } else if (width < 1200) {
        return $(".portrait").width("33%");
      } else if (width < 1700) {
        return $(".portrait").width("24.75%");
      } else {
        return $(".portrait").width("16.35%");
      }
    };
    setSpecificPeopleStyles = function() {
      var width;
      width = $(window).width();
      if (width < 1000) {
        $(".bannerImage").css({
          width: "96%",
          left: "2%"
        });
        $(".Name").css({
          left: "4%"
        });
        $(".info").css({
          left: "15%",
          width: "70%"
        });
        $("#AV").css({
          right: "4%"
        });
        $("#GDt").css({
          left: "3%",
          width: "41%"
        });
        return $("#AVt").css({
          right: "8%",
          width: "41%"
        });
      } else if (width < 1400) {
        $(".bannerImage").css({
          width: "80%",
          left: "10%"
        });
        $(".Name").css({
          left: "12%"
        });
        $(".info").css({
          left: "25%",
          width: "50%"
        });
        $("#AV").css({
          right: "12%"
        });
        $("#GDt").css({
          left: "12%",
          width: "32%"
        });
        return $("#AVt").css({
          right: "25%",
          width: "32%"
        });
      } else {
        $(".bannerImage").css({
          width: "60%",
          left: "20%"
        });
        $(".Name").css({
          left: "22%"
        });
        $(".info").css({
          left: "30%",
          width: "40%"
        });
        $("#AV").css({
          right: "22%"
        });
        $("#GDt").css({
          left: "22%",
          width: "25%"
        });
        return $("#AVt").css({
          right: "25%",
          width: "25%"
        });
      }
    };
    $(window).bind('resize', function() {
      setTextWidthSize();
      setPortraitWidth();
      return setSpecificPeopleStyles();
    });
    setTextWidthSize();
    setPortraitWidth();
    return setSpecificPeopleStyles();
  };

  setAndBindHowPageSizes = function() {
    var setFontSize, setTitleFontSize, setWidths, width;
    width = $(window).width();
    setTitleFontSize = function() {
      var s;
      s = Math.floor($("#teachingMasha").height() / 6);
      return $(".title, #inspiTitle").css({
        "font-size": s
      });
    };
    setWidths = function() {
      width = $(window).width();
      if (width < 1000) {
        $("article").css({
          left: "5%",
          right: "5%",
          width: "90%"
        });
        $(".aboutImage").css({
          width: "96%"
        });
        $(".tool").css({
          right: "45%",
          width: "50%"
        });
        $(".tool-text").css({
          width: "40%",
          left: "50%"
        });
        $("#actionTitleImage").css({
          width: "90%",
          left: "5%"
        });
        $("#actionText").css({
          width: "26%",
          top: "20%",
          left: "58%"
        });
        return $(".inspirationImage").css({
          width: "90%"
        });
      } else {
        $("article").css({
          left: "30%",
          right: "30%",
          width: "40%"
        });
        $(".aboutImage").css({
          width: "80%"
        });
        $(".tool").css({
          right: "12%",
          width: "40%"
        });
        $(".tool-text").css({
          width: "25%",
          left: "55%"
        });
        $("#actionTitleImage").css({
          width: "50%",
          left: "10%"
        });
        $("#actionText").css({
          width: "22%",
          top: "26%",
          left: "62.5%"
        });
        return $(".inspirationImage").css({
          width: "80%"
        });
      }
    };
    setFontSize = function() {
      var size, titleSize;
      width = $(window).width();
      size = Math.floor(width / 180) * 2;
      titleSize = Math.floor(size * 0.6) * 2;
      if (size > 18) {
        $(".tool-text p, article p, #actionText, #settingText p").css({
          "font-size": size
        });
        return $(".tool-text h2, #settingText h2, .inspiration-link").css({
          "font-size": titleSize
        });
      } else {
        $(".tool-text p, article p, #actionText, #settingText p").css({
          "font-size": 18
        });
        return $(".tool-text h2, #settingText h2, .inspiration-link").css({
          "font-size": "1.5em"
        });
      }
    };
    $(window).bind('resize', function() {
      setTitleFontSize();
      setWidths();
      return setFontSize();
    });
    setTitleFontSize();
    setWidths();
    return setFontSize();
  };

  exitPage = function(destination) {
    var go;
    go = function() {
      return window.location.href = destination;
    };
    $("#headerBar").fadeOut(400);
    $(".pane").fadeOut(400);
    return window.setTimeout(go, 400);
  };

}).call(this);
