// Generated by CoffeeScript 1.6.3
(function() {
  var buildNavFunctions, exitPage, loadpage;

  loadpage = function() {
    buildNavFunctions();
    $("#headerBar").hide().fadeIn(1000);
    return $(".pane").hide().fadeIn(1000);
  };

  $(document).ready(function() {
    return loadpage();
  });

  exitPage = function(destination) {
    var go;
    go = function() {
      return window.location.href = destination;
    };
    $("#headerBar").fadeOut(800);
    $(".pane").fadeOut(800);
    return window.setTimeout(go, 800);
  };

  buildNavFunctions = function() {
    $("#Gallery").click(function() {
      return exitPage("gallery.html");
    });
    $("#Contact").click(function() {
      return exitPage("404.html");
    });
    return $("#headerBarLogo").click(function() {
      return exitPage("index.html");
    });
  };

}).call(this);
