// Generated by CoffeeScript 1.6.1
(function() {
  var ListItem, addBack, addFront, buildNavFunctions, centerSelectedImage, deleteListItem, exitPage, galleryImageWidth, images, loadBottomBarImages, loadPage, numberOfGalleryImages, reloadPage, removeBack, removeFront, resizeBottomBar, resizeTheImage, selectIcon, selected, slideLeft, slideRight;

  images = [];

  selected = 9;

  numberOfGalleryImages = 30;

  galleryImageWidth = 120;

  $(document).ready(function() {
    return loadPage();
  });

  loadPage = function() {
    reloadPage();
    $("#headerBar").hide().fadeIn(1000);
    $("#theImage").hide().fadeIn(1000);
    $("#bottomBar").hide().fadeIn(1000);
    return $(window).bind('resize', function() {
      return reloadPage();
    });
  };

  reloadPage = function() {
    buildNavFunctions();
    resizeTheImage();
    return loadBottomBarImages();
  };

  buildNavFunctions = function() {
    $("#About").click(function() {
      return exitPage("about.html");
    });
    $("#headerBarLogo").click(function() {
      return exitPage("index.html");
    });
    return $("#Contact").click(function() {
      return exitPage("mailto:zfrenchee@gmail.com");
    });
  };

  resizeTheImage = function() {
    var desiredImageHeight, windowHeight;
    windowHeight = $(window).height();
    desiredImageHeight = windowHeight - 230;
    return $("#theImage").height(desiredImageHeight);
  };

  resizeBottomBar = function() {
    var desiredWidth, windowWidth;
    windowWidth = $(window).width();
    desiredWidth = windowWidth + 122 * 2;
    $("#bottomBar").width(desiredWidth);
    return desiredWidth;
  };

  loadBottomBarImages = function() {
    var $bottomBar, i, numberOfIconsToDisplay, _i, _j, _len, _results;
    numberOfIconsToDisplay = Math.floor(resizeBottomBar() / galleryImageWidth);
    for (i = _i = 1; 1 <= numberOfIconsToDisplay ? _i <= numberOfIconsToDisplay : _i >= numberOfIconsToDisplay; i = 1 <= numberOfIconsToDisplay ? ++_i : --_i) {
      images.push(i);
    }
    $bottomBar = $("#bottomBar");
    $bottomBar.empty();
    _results = [];
    for (_j = 0, _len = images.length; _j < _len; _j++) {
      i = images[_j];
      _results.push($bottomBar.append(ListItem(i)));
    }
    return _results;
  };

  ListItem = function(id) {
    var $li, url;
    url = "url(\"images/portfolio/lightpainting/icons/" + id + ".jpg\")";
    $li = $("<li/>", {
      "class": "fade",
      id: "" + id,
      style: "background-image: " + url + ";"
    });
    $li.click(function(e) {
      return selectIcon(e.target.id);
    });
    return $li;
  };

  deleteListItem = function(id) {
    return $("#" + id).remove();
  };

  selectIcon = function(id) {
    var $theImage, url;
    selected = parseInt(id);
    centerSelectedImage();
    $theImage = $("#theImage");
    url = "images/portfolio/lightpainting/" + selected + ".jpg";
    if ($theImage.attr('src') !== url) {
      return $theImage.fadeTo(100, 0, function() {
        return $(this).attr('src', url).load(function() {
          return $(this).fadeTo(100, 1.0);
        });
      });
    }
  };

  centerSelectedImage = function() {
    if (images.indexOf(selected) > images.length * 0.7) {
      return slideLeft();
    } else if (images.indexOf(selected) < images.length * 0.3) {
      return slideRight();
    } else {

    }
  };

  slideLeft = function() {
    removeFront();
    $("#bottomBar").addClass('slideLeft');
    return window.setTimeout(function() {
      addBack();
      $("#bottomBar").removeClass('slideLeft');
      return $("#bottomBar").css({
        "padding-left": "0px"
      });
    }, 200);
  };

  slideRight = function() {
    $("#bottomBar").addClass('slideRight');
    return window.setTimeout(function() {
      addFront();
      $("#bottomBar").removeClass('slideRight');
      $("#bottomBar").css({
        "padding-left": "0px"
      });
      return removeBack();
    }, 200);
  };

  removeFront = function() {
    return deleteListItem(images.shift());
  };

  removeBack = function() {
    return deleteListItem(images.pop());
  };

  addFront = function() {
    var image;
    image = theImageBefore(images[0]);
    images.unshift(image);
    return $("#bottomBar").prepend(ListItem(image));
  };

  addBack = function() {
    var image;
    image = theImageAfter(images[images.length - 1]);
    images.push(image);
    return $("#bottomBar").append(ListItem(image));
  };

  window.theImageBefore = function(id) {
    if (id - 1 !== 0) {
      return id - 1;
    } else {
      return numberOfGalleryImages;
    }
  };

  window.theImageAfter = function(id) {
    if (id + 1 > numberOfGalleryImages) {
      return 1;
    } else {
      return id + 1;
    }
  };

  $(document).keydown(function(e) {
    if (e.keyCode === 37 || e.keyCode === 40) {
      return selectIcon(theImageBefore(selected));
    } else if (e.keyCode === 32 || e.keyCode === 38 || e.keyCode === 39) {
      return selectIcon(theImageAfter(selected));
    } else {

    }
  });

  exitPage = function(destination) {
    var go;
    go = function() {
      return window.location.href = destination;
    };
    $("#headerBar").fadeOut(400);
    $("#theImage").fadeOut(400);
    $("#bottomBar").fadeOut(400);
    return window.setTimeout(go, 400);
  };

}).call(this);
