// Generated by CoffeeScript 1.8.0
(function() {
  var goToGallery, preload, preloadGalleryImages, prepareEnterSite;

  $(document).ready(function() {
    $.backstretch('images/graphics/index.jpg', {
      speed: 3000
    });
    return preloadGalleryImages();
  });

  $(document).on("backstretch.show", function() {
    return prepareEnterSite();
  });

  preloadGalleryImages = function() {
    var gallery, i, _i;
    gallery = [];
    for (i = _i = 1; _i <= 30; i = ++_i) {
      gallery.push("images/portfolio/lightpainting/" + i + ".jpg");
      gallery.push("images/portfolio/lightpainting/icons/" + i + ".jpg");
    }
    return preload(gallery);
  };

  preload = function(array) {
    return $(array).each(function() {
      return $('<img/>')[0].src = this;
    });
  };

  prepareEnterSite = function() {
    var $enterSite;
    $enterSite = $("#enterSite");
    return $enterSite.delay(10).fadeIn(3000, function() {
      return $enterSite.addClass("fade2").click(function() {
        $enterSite.removeClass("fade2").fadeOut(800);
        $(".backstretch").fadeOut(2000);
        return window.setTimeout(goToGallery, 2000);
      });
    });
  };

  goToGallery = function() {
    return window.location.href = "gallery.html";
  };


  /*
  
  operatingSystem = () ->
  
  	if navigator.appVersion.indexOf("Mac") isnt -1
  		return "Enter fullscreen for a better view (⌘ + F11)"
  
  	if navigator.appVersion.indexOf("Win") isnt -1 
  		return "Enter fullscreen for a better view (press F11)"
  
  	else return undefined
   */

}).call(this);
