// Generated by CoffeeScript 1.6.1
(function() {
  var buildNavFunctions, exitPage, howWeDidIt, loadpage, setAndBindHowPageSizes;

  $(document).ready(function() {
    return loadpage();
  });

  loadpage = function() {
    buildNavFunctions();
    setAndBindHowPageSizes();
    $("#headerBar").hide().fadeIn(1000);
    return howWeDidIt();
  };

  buildNavFunctions = function() {
    $("#Gallery").click(function() {
      return exitPage("gallery.html");
    });
    $("#About").click(function() {
      return exitPage('about.html');
    });
    return $("#headerBarLogo").click(function() {
      return exitPage("index.html");
    });
  };

  howWeDidIt = function() {
    setAndBindHowPageSizes();
    return $("#method").removeClass("hidden").fadeIn(1000);
  };

  setAndBindHowPageSizes = function() {
    var setFontSize, setTitleFontSize, width;
    width = $(window).width();
    setTitleFontSize = function() {
      var s;
      s = Math.floor($("#teachingMasha").height() / 6);
      return $(".title, #inspiTitle").css({
        "font-size": s
      });
    };
    setFontSize = function() {
      var size, titleSize;
      width = $(window).width();
      size = Math.floor(width / 180) * 2;
      titleSize = Math.floor(size * 0.6) * 2;
      if (size > 18) {
        $(".tool-text p, article p, #actionText, #settingText p").css({
          "font-size": size
        });
        return $(".tool-text h2, #settingText h2, .inspiration-link").css({
          "font-size": titleSize
        });
      } else {
        $(".tool-text p, article p, #actionText, #settingText p").css({
          "font-size": 18
        });
        return $(".tool-text h2, #settingText h2, .inspiration-link").css({
          "font-size": "1.5em"
        });
      }
    };
    $(window).bind('resize', function() {
      setTitleFontSize();
      return setFontSize();
    });
    setTitleFontSize();
    return setFontSize();
  };

  exitPage = function(destination) {
    var go;
    go = function() {
      return window.location.href = destination;
    };
    $("#headerBar").fadeOut(400);
    $(".pane").fadeOut(400);
    return window.setTimeout(go, 400);
  };

}).call(this);
