// Generated by CoffeeScript 1.8.0
(function() {
  var Xenophos, addToCurrentPanes, back, buildNavFunctions, buildPortraitFor, clearAllCurrentPanes, currentPanes, exitPage, getCurrentPanes, loadpage, meetUs, removeFromCurrentPane, showSpecificBio,
    __slice = [].slice;

  Xenophos = [
    {
      firstname: "Alex",
      lastname: "Lenail",
      tags: ["Co-founder", "Light-painter", "Webmaster"]
    }, {
      firstname: "Bradford",
      lastname: "Thorne",
      tags: ["Co-founder", "Light-painter", "Photographer"]
    }, {
      firstname: "Max",
      lastname: "Lenail",
      tags: ["Co-founder", "Lead Photographer"]
    }, {
      firstname: "Anna",
      lastname: "McGarrigle",
      tags: ["Photographer", "Web Designer"]
    }, {
      firstname: "Masha",
      lastname: "Andreyeva",
      tags: ["Photographer", "Light-painter"]
    }, {
      firstname: "Arun",
      lastname: "Varma",
      tags: ["Photographer", "Light-painter"]
    }, {
      firstname: "Gregory",
      lastname: "Dunn",
      tags: ["Light-painter"]
    }, {
      firstname: "Tiffany",
      lastname: "Tsung",
      tags: ["Light-painter"]
    }, {
      firstname: "Paige",
      lastname: "Morkner",
      tags: ["Light-painter"]
    }, {
      firstname: "Eric",
      lastname: "Theis",
      tags: ["Light-painter"]
    }, {
      firstname: "Kevin",
      lastname: "Lee",
      tags: ["Light-painter"]
    }, {
      firstname: "Jason",
      lastname: "Liang",
      tags: ["Light-painter"]
    }
  ];

  currentPanes = [];

  addToCurrentPanes = function() {
    var pane, panes, _i, _len, _results;
    panes = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = panes.length; _i < _len; _i++) {
      pane = panes[_i];
      _results.push(currentPanes.push(pane));
    }
    return _results;
  };

  removeFromCurrentPane = function(pane) {
    return currentPanes.splice(indexOf(pane), 1);
  };

  clearAllCurrentPanes = function() {
    return currentPanes = [];
  };

  getCurrentPanes = function() {
    return currentPanes;
  };

  $(document).ready(function() {
    return loadpage();
  });

  loadpage = function() {
    buildNavFunctions();
    $("#headerBar").hide().fadeIn(1000);
    return meetUs();
  };

  buildNavFunctions = function() {
    $("#Gallery").click(function() {
      return exitPage("gallery.html");
    });
    $("#About").click(function() {
      return exitPage('about.html');
    });
    $("#headerBarLogo").click(function() {
      return exitPage("index.html");
    });
    $(".backButton").click(function() {
      return back();
    });
    return $("#Contact").click(function() {
      return exitPage("mailto:zfrenchee@gmail.com");
    });
  };

  meetUs = function() {
    var $people, person, _i, _len;
    $people = $("#people");
    $people.children().each(function() {
      return $(this).remove();
    });
    $people.removeClass("hidden").fadeIn(1);
    addToCurrentPanes($people);
    for (_i = 0, _len = Xenophos.length; _i < _len; _i++) {
      person = Xenophos[_i];
      buildPortraitFor(person);
    }
    return $('body').animate({
      scrollTop: 100
    }, 1000);
  };

  buildPortraitFor = function(person) {
    var $image, $nametag, $portrait, name, tags;
    $portrait = $("<div/>", {
      "class": "hidden portrait",
      id: "" + person.firstname
    });
    $image = $("<img/>", {
      src: "images/about/icons/" + person.firstname + ".jpg"
    });
    name = "<h1>" + person.firstname + " " + person.lastname + "</h1>";
    tags = "<p>" + person.tags.join(", &nbsp") + "</p>";
    $nametag = $("<div/>", {
      "class": "nametag"
    }).append(name).append(tags);
    $portrait.append($image).append($nametag);
    $("#people").append($portrait);
    $portrait.removeClass("hidden").addClass("popIn");
    return $portrait.click(function() {
      $('body').animate({
        scrollTop: 0
      }, 200);
      return showSpecificBio(person.firstname);
    });
  };

  showSpecificBio = function(name) {
    var $div, oldPane, _i, _len, _ref;
    switch (name) {
      case "Alex":
        $div = $("#Alex_Lenail");
        break;
      case "Bradford":
        $div = $("#Bradford_Thorne");
        break;
      case "Max":
        $div = $("#Max_Lenail");
        break;
      case "Anna":
        $div = $("#Anna_McGarrigle");
        break;
      case "Masha":
        $div = $("#Masha_Andreyeva");
        break;
      case "Arun":
        $div = $("#Arun_Varma_Gregory_Dunn");
        break;
      case "Gregory":
        $div = $("#Arun_Varma_Gregory_Dunn");
        break;
      case "Tiffany":
      case "Paige":
      case "Eric":
        $div = $("#Tiffany_Tsung_Paige_Morkner_Eric_Theis");
        break;
      case "Kevin":
      case "Jason":
        $div = $("#Kevin_Lee_Allen_Lee_Jason_Liang");
        break;
      default:
        throw new Error("Name unrecognized");
    }
    _ref = getCurrentPanes();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      oldPane = _ref[_i];
      oldPane.fadeOut(200);
    }
    $div.removeClass("hidden").fadeIn(600);
    $div.children().each(function() {
      return $(this).removeClass("hidden").fadeIn(600);
    });
    return addToCurrentPanes($div);
  };

  back = function() {
    var newPane, next, oldPane, oldPanes, _fn, _i, _j, _len, _len1, _results;
    oldPanes = getCurrentPanes();
    if (oldPanes[0].selector === "#people" && (oldPanes[1] != null)) {
      next = [$("#people")];
      $('body').animate({
        scrollTop: 100
      }, 1000);
    } else {
      next = [$("#who"), $("#what")];
    }
    _fn = function(oldPane) {
      return oldPane.fadeOut(400);
    };
    for (_i = 0, _len = oldPanes.length; _i < _len; _i++) {
      oldPane = oldPanes[_i];
      _fn(oldPane);
    }
    clearAllCurrentPanes();
    _results = [];
    for (_j = 0, _len1 = next.length; _j < _len1; _j++) {
      newPane = next[_j];
      newPane.fadeIn(400);
      _results.push(addToCurrentPanes(newPane));
    }
    return _results;
  };

  exitPage = function(destination) {
    var go;
    go = function() {
      return window.location.href = destination;
    };
    $("#headerBar").fadeOut(400);
    $(".pane").fadeOut(400);
    return window.setTimeout(go, 400);
  };

}).call(this);
